apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vj3c1dzsj-java-quarkus
  janus-idp.io/tekton: vj3c1dzsj-java-quarkus
  backstage.io/kubernetes-id: vj3c1dzsj-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vj3c1dzsj-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
